name: Trigger CI process

on:
  workflow_run:
    workflows: ["CI process for Todo-List"]
    types:
      - completed
      
jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
