name: Trigger CI process

on:
  workflow_run:
    workflows: ["CI process for Todo-List"]
    types:
      - completed
      
jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v


  trigger-a-jenkins-job:
    runs-on: ubuntu-latest
    
    steps: 
      - id: triggerjenkinsjob
        uses: mickeygoussetorg/trigger-jenkins-job@v1
        with:
          jenkins-server:
          jenkins-job: "SymfonyTodo"
          jenkins-username:
          jenkins-pat: 
          poll-time: 10
          timeout-value: 600
          verbose: true
          
